const SELECT_LIST = 'SELECT_LIST';
const ADD_LIST = 'ADD_LIST';
const REMOVE_LIST = 'REMOVE_LIST';
const BULK_ADD_LIST_ITEM = 'BULK_ADD_LIST_ITEM';
const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
const INCREASE_VOTE = 'INCREASE_VOTE';
const DECREASE_VOTE = 'DECREASE_VOTE';

export {
  SELECT_LIST,
  ADD_LIST,
  REMOVE_LIST,
  BULK_ADD_LIST_ITEM,
  ADD_LIST_ITEM,
  REMOVE_LIST_ITEM,
  INCREASE_VOTE,
  DECREASE_VOTE
};
